name: Format

on:
  pull_request:
    branches: [ "main" ]
  pull_request_target:
    types:
      - labeled 

jobs:
  format:
    runs-on: macos-latest

    permissions:
      contents: write # Required for internal PRs to allow auto-commits

    name: Lint and format
    steps:
    - name: Checkout for internal PR
      if: ${{ github.event.pull_request.head.repo.owner.login == github.repository_owner }}
      uses: actions/checkout@v4
      with:
        # Use PAT which has write access
        token: ${{ secrets.PAT }}
        ref: ${{ github.head_ref }}

    - name: Checkout for external PR
      if: ${{ github.event.pull_request.head.repo.owner.login != github.repository_owner }}
      uses: actions/checkout@v4
    
    - name: Install swift-format
      run: brew install swift-format

    - name: Format
      run: swift-format format --in-place --parallel --recursive Sources/ Tests/
    
    - name: Check for formatting changes
      id: check_changes
      run: |
        git diff --exit-code
      continue-on-error: true

    - name: Check if PR has a specific label
      id: check_label
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          const labelToCheck = 'auto-format';
          const prLabels = context.payload.pull_request.labels.map(label => label.name);
          return prLabels.includes(labelToCheck);

    - name: Apply auto-formatting
      if: >
        steps.check_changes.outcome == 'failure' &&
        steps.check_label.outputs.result == 'true' &&
        github.event.pull_request.head.repo.owner.login == github.repository_owner
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Apply auto-formatting

    - name: Fail if changes detected (optional)
      if: >
        steps.check_changes.outcome == 'failure' &&
        (
          github.event.pull_request.head.repo.owner.login != github.repository_owner || 
          steps.check_label.outputs.result == 'false'
        )
      run: |
        echo "::error::Formatting issues detected. Please fix them."
        echo "Run 'swift-format format --in-place --parallel --recursive Sources/ Tests/' locally to fix formatting."
        exit 1

    - name: Lint
      id: lint 
      run: |
        swift-format lint --strict --parallel --recursive Sources/ Tests/
